// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: clean_users.sql

package database

import (
	"context"
)

const cleanUsers = `-- name: CleanUsers :exec
TRUNCATE TABLE users CASCADE
`

func (q *Queries) CleanUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanUsers)
	return err
}
