// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: feed.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const insertFeed = `-- name: InsertFeed :one
INSERT INTO feed (name, url, user_id)
VALUES ($1,$2,$3)
RETURNING name, url, user_id
`

type InsertFeedParams struct {
	Name   string
	Url    string
	UserID uuid.UUID
}

func (q *Queries) InsertFeed(ctx context.Context, arg InsertFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, insertFeed, arg.Name, arg.Url, arg.UserID)
	var i Feed
	err := row.Scan(&i.Name, &i.Url, &i.UserID)
	return i, err
}
