// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_feed_name_from_user.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFeedNameFromUser = `-- name: GetFeedNameFromUser :one
select
    feed.name
from feed_follows
inner join feed
    on feed.id = feed_follows.feed_id
where feed_follows.user_id = $1
`

func (q *Queries) GetFeedNameFromUser(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getFeedNameFromUser, userID)
	var name string
	err := row.Scan(&name)
	return name, err
}
