// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_all_feeds.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAllFeeds = `-- name: GetAllFeeds :many
select
    feed.name,
    feed.url,
    feed.user_id,
    users.name as username
from feed
inner join users
    on users.id = feed.user_id
order by feed.name asc
`

type GetAllFeedsRow struct {
	Name     string
	Url      string
	UserID   uuid.UUID
	Username string
}

func (q *Queries) GetAllFeeds(ctx context.Context) ([]GetAllFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFeedsRow
	for rows.Next() {
		var i GetAllFeedsRow
		if err := rows.Scan(
			&i.Name,
			&i.Url,
			&i.UserID,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
