// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_next_feed_to_fetch.sql

package database

import (
	"context"
)

const getNextFeedToFetch = `-- name: GetNextFeedToFetch :one
select 
    url
from feed
order by last_fetched_at nulls FIRST
limit 1
`

func (q *Queries) GetNextFeedToFetch(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getNextFeedToFetch)
	var url string
	err := row.Scan(&url)
	return url, err
}
