// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_post_from_description_and_url.sql

package database

import (
	"context"
	"database/sql"
)

const checkIfPostExists = `-- name: CheckIfPostExists :one
select
    title,
    url,
    description
from posts
where description = $1
    and url = $2
`

type CheckIfPostExistsParams struct {
	Description sql.NullString
	Url         string
}

type CheckIfPostExistsRow struct {
	Title       string
	Url         string
	Description sql.NullString
}

func (q *Queries) CheckIfPostExists(ctx context.Context, arg CheckIfPostExistsParams) (CheckIfPostExistsRow, error) {
	row := q.db.QueryRowContext(ctx, checkIfPostExists, arg.Description, arg.Url)
	var i CheckIfPostExistsRow
	err := row.Scan(&i.Title, &i.Url, &i.Description)
	return i, err
}
