// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_feed_from_url.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFeedFromURL = `-- name: GetFeedFromURL :one
select
    feed.id as feed_id,
    feed.name,
    feed.url,
    feed.user_id
from feed
where feed.url = $1
`

type GetFeedFromURLRow struct {
	FeedID uuid.UUID
	Name   string
	Url    string
	UserID uuid.UUID
}

func (q *Queries) GetFeedFromURL(ctx context.Context, url string) (GetFeedFromURLRow, error) {
	row := q.db.QueryRowContext(ctx, getFeedFromURL, url)
	var i GetFeedFromURLRow
	err := row.Scan(
		&i.FeedID,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}
