// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_user.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUser = `-- name: GetUser :one
SELECT
    id,
    updated_at,
    created_at,
    name
FROM users
WHERE name = $1
`

type GetUserRow struct {
	ID        uuid.UUID
	UpdatedAt time.Time
	CreatedAt time.Time
	Name      string
}

func (q *Queries) GetUser(ctx context.Context, name string) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, name)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Name,
	)
	return i, err
}
