// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: insert_feed.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const insertFeed = `-- name: InsertFeed :one
INSERT INTO feed (id, name, url, user_id)
VALUES ($1,$2,$3,$4)
RETURNING id, name, url, user_id
`

type InsertFeedParams struct {
	ID     uuid.UUID
	Name   string
	Url    string
	UserID uuid.UUID
}

func (q *Queries) InsertFeed(ctx context.Context, arg InsertFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, insertFeed,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}
