// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: insert_feed.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const insertFeed = `-- name: InsertFeed :one
INSERT INTO feed (id, name, url, user_id, last_fetched_at)
VALUES ($1,$2,$3,$4,$5)
RETURNING id, name, url, user_id, last_fetched_at
`

type InsertFeedParams struct {
	ID            uuid.UUID
	Name          string
	Url           string
	UserID        uuid.UUID
	LastFetchedAt sql.NullTime
}

func (q *Queries) InsertFeed(ctx context.Context, arg InsertFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, insertFeed,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.UserID,
		arg.LastFetchedAt,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}
