// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: update_feed_last_fetch.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const updateFetchDate = `-- name: UpdateFetchDate :one
update feed
set last_fetched_at = $1
where id = $2

RETURNING id, name, url, user_id, last_fetched_at
`

type UpdateFetchDateParams struct {
	LastFetchedAt sql.NullTime
	ID            uuid.UUID
}

func (q *Queries) UpdateFetchDate(ctx context.Context, arg UpdateFetchDateParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, updateFetchDate, arg.LastFetchedAt, arg.ID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}
